/**
 * @property {boolean} game.sdkActive
 * @property {boolean} game.paused
 * @property {number} game.pluginVersion
 * @property {number} game.version
 * @property {number} game.telemetryVersion
 * @property {number} game.maxTrailerCount
 * @property {number} game.scale
 * @property {number} game.game.id
 * @property {string} game.game.name
 * @property {number} game.time.value
 * @property {number} game.time.unix
 * @property {number} truck.transmission.forwardGears
 * @property {number} truck.transmission.reverseGears
 * @property {number} truck.transmission.selectors
 * @property {number} truck.transmission.slot
 * @property {number} truck.transmission.damage
 * @property {string} truck.transmission.shifterType
 * @property {number} truck.brakes.retarder.steps
 * @property {number} truck.brakes.retarder.level
 * @property {number} truck.brakes.airPressure.value
 * @property {number} truck.brakes.temperature.value
 * @property {boolean} truck.brakes.parking.enabled
 * @property {boolean} truck.brakes.motor.enabled
 * @property {number} truck.lights.auxFront.value
 * @property {number} truck.lights.auxRoof.value
 * @property {number} truck.lights.dashboardBacklight
 * @property {boolean} truck.lights.blinker.left.enabled
 * @property {boolean} truck.lights.blinker.left.active
 * @property {boolean} truck.lights.blinker.right.enabled
 * @property {boolean} truck.lights.blinker.right.active
 * @property {boolean} truck.lights.parking.enabled
 * @property {boolean} truck.lights.beamLow.enabled
 * @property {boolean} truck.lights.beamHigh.enabled
 * @property {boolean} truck.lights.beacon.enabled
 * @property {boolean} truck.lights.brake.enabled
 * @property {boolean} truck.lights.reverse.enabled
 * @property {boolean} truck.lights.hazard.enabled
 * @property {number} truck.fuel.capacity
 * @property {number} truck.fuel.value
 * @property {number} truck.fuel.avgConsumption
 * @property {number} truck.fuel.range
 * @property {number} truck.adBlue.capacity
 * @property {number} truck.adBlue.value
 * @property {number} truck.engine.damage
 * @property {boolean} truck.engine.enabled
 * @property {number} truck.differential.ratio
 * @property {boolean} truck.differential.lock.enabled
 * @property {number} truck.speed.value
 * @property {number} truck.speed.kph
 * @property {number} truck.speed.mph
 * @property {number} truck.cruiseControl.value
 * @property {number} truck.cruiseControl.kph
 * @property {number} truck.cruiseControl.mph
 * @property {boolean} truck.cruiseControl.enabled
 * @property {number} truck.cabin.damage
 * @property {number} truck.chassis.damage
 * @property {number} truck.odometer
 * @property {boolean} truck.electric.enabled
 * @property {boolean} truck.wipers.enabled
 * @property {boolean} truck.liftAxle.enabled
 * @property {boolean} truck.liftAxle.indicator.enabled
 * @property {string} truck.make.id
 * @property {string} truck.make.name
 * @property {string} truck.model.id
 * @property {string} truck.model.name
 * @property {string} truck.licensePlate.value
 * @property {string} truck.licensePlate.country.id
 * @property {string} truck.licensePlate.country.name
 * @property {number} truck.damage.cabin
 * @property {number} truck.damage.chassis
 * @property {number} truck.damage.engine
 * @property {number} truck.damage.transmission
 * @property {number} truck.damage.wheels
 * @property {number} truck.damage.total
 * @property {string} truck.brand.id
 * @property {string} truck.brand.name
 * @property {number} job.expectedDeliveryTimestamp.value
 * @property {number} job.expectedDeliveryTimestamp.unix
 * @property {number} job.plannedDistance.km
 * @property {number} job.plannedDistance.miles
 * @property {number} job.cargo.mass
 * @property {number} job.cargo.unitMass
 * @property {number} job.cargo.damage
 * @property {boolean} job.cargo.isLoaded
 * @property {string} job.cargo.id
 * @property {string} job.cargo.name
 * @property {boolean} job.isSpecial
 * @property {string} job.destination.city.id
 * @property {string} job.destination.city.name
 * @property {string} job.destination.company.id
 * @property {string} job.destination.company.name
 * @property {string} job.source.city.id
 * @property {string} job.source.city.name
 * @property {string} job.source.company.id
 * @property {string} job.source.company.name
 * @property {string} job.market.id
 * @property {string} job.market.name
 * @property {number} job.income
 * @property {boolean} trailer.attached
 * @property {number} trailer.cargo.damage
 * @property {number} trailer.chassis.damage
 * @property {number} trailer.body.damage
 * @property {string} trailer.model.id
 * @property {string} trailer.model.name
 * @property {string} trailer.accessoryId
 * @property {string} trailer.bodyType
 * @property {string} trailer.make.id
 * @property {string} trailer.make.name
 * @property {string} trailer.chainType
 * @property {string} trailer.licensePlate.value
 * @property {string} trailer.licensePlate.country.id
 * @property {string} trailer.licensePlate.country.name
 * @property {number} trailer.damage.cargo
 * @property {number} trailer.damage.chassis
 * @property {number} trailer.damage.wheels
 * @property {number} trailer.damage.body
 * @property {number} trailer.damage.total
 * @property {boolean} trailer.liftAxle.enabled
 * @property {boolean} trailer.liftAxle.indicator.enabled
 * @property {string} trailer.brand.id
 * @property {string} trailer.brand.name
 * @property {number} events.job.delivered.timeTaken
 * @property {number} events.job.delivered.startedTimestamp.value
 * @property {number} events.job.delivered.startedTimestamp.unix
 * @property {number} events.job.delivered.deliveredTimestamp.value
 * @property {number} events.job.delivered.deliveredTimestamp.unix
 * @property {number} events.job.delivered.earnedXP
 * @property {number} events.job.delivered.cargoDamage
 * @property {number} events.job.delivered.distance.km
 * @property {number} events.job.delivered.distance.miles
 * @property {boolean} events.job.delivered.autoParked
 * @property {number} events.job.delivered.revenue
 * @property {boolean} events.job.delivered.active
 * @property {boolean} events.job.started.autoLoaded
 * @property {boolean} events.job.started.active
 * @property {number} events.job.cancelled.penalty
 * @property {boolean} events.job.cancelled.active
 * @property {number} events.job.cancelled.startedTimestamp.value
 * @property {number} events.job.cancelled.startedTimestamp.unix
 * @property {number} events.job.cancelled.cancelledTimestamp.value
 * @property {number} events.job.cancelled.cancelledTimestamp.unix
 * @property {boolean} events.job.finished.active
 * @property {number} events.refuelPaid.amount
 * @property {boolean} events.refuelPaid.active
 * @property {string} events.fine.offence.id
 * @property {string} events.fine.offence.name
 * @property {number} events.fine.amount
 * @property {boolean} events.fine.active
 * @property {string} events.ferry.source.id
 * @property {string} events.ferry.source.name
 * @property {string} events.ferry.destination.id
 * @property {string} events.ferry.destination.name
 * @property {number} events.ferry.amount
 * @property {boolean} events.ferry.active
 * @property {string} events.ferry.target.id
 * @property {string} events.ferry.target.name
 * @property {string} events.train.source.id
 * @property {string} events.train.source.name
 * @property {string} events.train.destination.id
 * @property {string} events.train.destination.name
 * @property {number} events.train.amount
 * @property {boolean} events.train.active
 * @property {string} events.train.target.id
 * @property {string} events.train.target.name
 * @property {number} events.tollgate.amount
 * @property {boolean} events.tollgate.active
 * @property {boolean} events.refuel.active
 * @property {number} navigation.nextRestStop
 * @property {number} navigation.distance
 * @property {number} navigation.time
 * @property {number} navigation.speedLimit.value
 * @property {number} navigation.speedLimit.kph
 * @property {number} navigation.speedLimit.mph
 * @property {number} controls.input.steering
 * @property {number} controls.input.throttle
 * @property {number} controls.input.brake
 * @property {number} controls.input.clutch
 * @property {number} controls.game.steering
 * @property {number} controls.game.throttle
 * @property {number} controls.game.brake
 * @property {number} controls.game.clutch
 * @property {string[]} substances
 */